import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import Sidebar from ".././components/server/Sidebar";
import { cookies } from "next/headers";
import { CookiesProvider } from "next-client-cookies/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-row antialiased bg-gray-50`}
      >
        <CookiesProvider>
          <Sidebar />
          <div className={"w-[calc(100%-150px)]"}>{children}</div>
        </CookiesProvider>
      </body>
    </html>
  );
}
